services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goingmysocial
      MYSQL_USER: social
      MYSQL_PASSWORD: mysocialpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: goingmysocial-api
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      ConnectionStrings__MySQLConnection: "server=mysql-db;database=goingmysocial;user=root;password=root"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "5046:8080"
    networks:
      - app-network

  frontend-angular:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: goingmysocialnetwork
    depends_on:
      - backend-api
    ports:
      - "4200:80"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
